name: CI and Release
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  lint-and-test-types:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm
          cache-dependency-path: package-lock.json
          registry-url: 'https://npm.pkg.github.com'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Set up Clojure
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          cli: latest

      - name: Cache clojure dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
            .cpcache
          key: cljdeps-${{ hashFiles('deps.edn') }}
          restore-keys: cljdeps-

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Run type tests
        run: npm run test:types

  test-debug:
    needs: [lint-and-test-types]
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm
          cache-dependency-path: package-lock.json
          registry-url: 'https://npm.pkg.github.com'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Set up Clojure
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          cli: latest

      - name: Cache clojure dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
            .cpcache
          key: cljdeps-${{ hashFiles('deps.edn') }}
          restore-keys: cljdeps-

      - name: Install dependencies
        run: npm install

      - name: Prepare test
        run: npm run prepare:all

      - name: Setup Chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Setup Firefox
        id: setup-firefox
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: stable

      - name: Setup Edge
        id: setup-edge
        uses: browser-actions/setup-edge@v1
        with:
          edge-version: stable

      - name: Setup Opera
        id: setup-opera
        uses: browser-actions/setup-opera@v1
        with:
          opera-version: stable

      - name: Setup Safari
        if: matrix.os == 'macos-latest'
        id: setup-safari
        uses: browser-actions/setup-safari@v1
        with:
          safari-version: stable

      - name: Set KARMA_BROWSERS
        run: |
          if [ "$RUNNER_OS" == "Linux" ] || [ "$RUNNER_OS" == "Windows" ]; then
            echo "KARMA_BROWSERS=ChromeHeadlessNoSandbox,FirefoxHeadless,EdgeHeadless,OperaHeadless" >> $GITHUB_ENV
          elif [ "$RUNNER_OS" == "macOS" ]; then
            echo "KARMA_BROWSERS=ChromeHeadlessNoSandbox,FirefoxHeadless,EdgeHeadless,OperaHeadless,Safari" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Run headless tests
        run: npm run test:debug

      - name: Build demo (dev)
        run: npm run build:demo

      - name: Run sanity test (dev)
        env:
          CHROME_BIN: ${{ steps.setup-chrome.outputs.chrome-path }}
          FIREFOX_BIN: ${{ steps.setup-firefox.outputs.firefox-path }}
          EDGE_BIN: ${{ steps.setup-edge.outputs.edge-path }}
          OPERA_BIN: ${{ steps.setup-opera.outputs.opera-path }}
          SAFARI_BIN: ${{ steps.setup-safari.outputs.safari-path }}
        run: node scripts/test-demo.js

  test-release:
    needs: [lint-and-test-types]
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm
          cache-dependency-path: package-lock.json
          registry-url: 'https://npm.pkg.github.com'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Set up Clojure
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          cli: latest

      - name: Cache clojure dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
            .cpcache
          key: cljdeps-${{ hashFiles('deps.edn') }}
          restore-keys: cljdeps-

      - name: Install dependencies
        run: npm install

      - name: Prepare test
        run: npm run prepare:all

      - name: Setup Chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Setup Firefox
        id: setup-firefox
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: stable

      - name: Setup Edge
        id: setup-edge
        uses: browser-actions/setup-edge@v1
        with:
          edge-version: stable

      - name: Setup Opera
        id: setup-opera
        uses: browser-actions/setup-opera@v1
        with:
          opera-version: stable

      - name: Setup Safari
        if: matrix.os == 'macos-latest'
        id: setup-safari
        uses: browser-actions/setup-safari@v1
        with:
          safari-version: stable

      - name: Set KARMA_BROWSERS
        run: |
          if [ "$RUNNER_OS" == "Linux" ] || [ "$RUNNER_OS" == "Windows" ]; then
            echo "KARMA_BROWSERS=ChromeHeadlessNoSandbox,FirefoxHeadless,EdgeHeadless,OperaHeadless" >> $GITHUB_ENV
          elif [ "$RUNNER_OS" == "macOS" ]; then
            echo "KARMA_BROWSERS=ChromeHeadlessNoSandbox,FirefoxHeadless,EdgeHeadless,OperaHeadless,Safari" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Run headless advanced tests
        run: npm run test:release

      - name: Build demo (release)
        env:
          MODE: release
        run: npm run build:demo

      # Quick-and-dirty method for stripping the erroneous `goog=goog||{};`
      # statement from the compiled libs.
      # ----------------------------------------------------------------------
      # TODO: Replace this with a proper fix when possible. I had it fixed but
      # it snuck back in somehow ...
      # ----------------------------------------------------------------------
      - name: Strip goog
        run: node scripts/strip-goog.js dist/libs/lib.core.js

      - name: Run sanity test (release)
        env:
          CHROME_BIN: ${{ steps.setup-chrome.outputs.chrome-path }}
          FIREFOX_BIN: ${{ steps.setup-firefox.outputs.firefox-path }}
          EDGE_BIN: ${{ steps.setup-edge.outputs.edge-path }}
          OPERA_BIN: ${{ steps.setup-opera.outputs.opera-path }}
          SAFARI_BIN: ${{ steps.setup-safari.outputs.safari-path }}
        run: node scripts/test-demo.js

      - name: Upload libs artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: libs-artifact
          path: |
            dist/**
            types/**
            resources/public/extensions/**
            scripts/postinstall.js

  release:
    needs: [test-debug, test-release]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          registry-url: 'https://npm.pkg.github.com'

      - name: Download libs artifact
        uses: actions/download-artifact@v4
        with:
          name: libs-artifact
          path: .

      - name: Publish to GitHub Packages
        run: npm publish --access public
