name: CI Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
      - uses: DeLaGuardo/setup-clojure@13.4
        with:
          cli: latest
      - name: Cache clojure deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
            .cpcache
          key: cljdeps-${{ hashFiles('deps.edn') }}
          restore-keys: cljdeps-
      - run: npm install
      - run: npm run test:types
      - run: npm run test:headless
